64 feature/friend list/master
DoubleV37/ft_transcendence pull request #98
Opened 2024-04-17 08:55 UTC by V0lk7

Feature Friend List implemented and working how it was meaned.
Problem about the profile picture not changing when use of refresh button is solved now.

2024-04-17 09:09 UTC, ji2myji2my requested changes
Maybe do the transfert .html file from */FriendsList/template to the correct static file front

Kiss

2024-04-17 09:09 UTC, ji2myji2my commented on Django_data/apps/FriendsList/templates/RequestList copy.html
Delete this file

2024-04-17 09:09 UTC, ji2myji2my commented on Django_data/apps/FriendsList/views.py
> +            logger.info(f"{request.POST = }")
Delete debug code

2024-04-17 09:09 UTC, ji2myji2my commented on Django_data/apps/Twofa/views.py
> +            logger.info("The fuuuuuuuck ???")
Delete debug code

2024-04-17 10:34 UTC, ji2myji2my requested changes
Missing a feature

2024-04-17 12:32 UTC, ji2myji2my requested changes

2024-04-17 12:40 UTC, V0lk7 commented on Django_data/apps/FriendsList/views.py
> +            logger.info(f"{request.POST = }")
yeah yeah yeah

2024-04-17 14:17 UTC, DoubleV37 approved these changes
Gg great job

2024-04-18 06:44 UTC, ji2myji2my approved these changes
Great job, supreme manager, developer and friend Jean. Always a pleasure to work with you.

2024-04-18 06:50 UTC, merged

2024-04-18 06:51 UTC, ji2myji2my commented
Nice jobs team.